In [2]:
import pandas as pd

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("belbino/indian-banking-transactions-20192024")

print("Path to dataset files:", path)

C:\Users\santh\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\santh\.cache\kagglehub\datasets\belbino\indian-banking-transactions-20192024\2.archive...

100%|████████████████████████████████████████████████████████████████████████████| 17.4M/17.4M [00:02<00:00, 6.59MB/s]

Extracting files...

Path to dataset files: C:\Users\santh\.cache\kagglehub\datasets\belbino\indian-banking-transactions-20192024\versions\2

In [5]:
df = pd.read_csv("indian_banking_transactions.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 550000
Columns: 20

In [6]:
df.head()

,transaction_id,customer_id,transaction_date,transaction_time,account_type,transaction_type,transaction_amount,transaction_direction,account_balance,merchant_category,state,credit_score,has_loan,loan_type,emi_amount,transaction_status,channel,kyc_status,is_fraud,transaction_hour
0,TXN000000001,CUST015796,2019-01-01,15:28,Current,UPI,1820.17,Debit,609365.31,Food & Dining,Maharashtra,764,0,NaN,0.00,Success,Branch,Verified,0,15
1,TXN000000002,CUST000861,2019-01-01,03:00,Current,UPI,392.67,Credit,14451.14,Education,West Bengal,630,0,NaN,0.00,Success,Mobile_App,Verified,0,3
2,TXN000000003,CUST076821,2019-01-01,18:03,Fixed Deposit,POS,1255.97,Debit,47621.87,Utilities,Punjab,813,1,Home,1433.91,Success,Mobile_App,Verified,0,18
3,TXN000000004,CUST054887,2019-01-01,08:03,Savings,UPI,2580.68,Debit,34467.85,Travel,Karnataka,628,1,Personal,6280.35,Success,API,Verified,0,8
4,TXN000000005,CUST006266,2019-01-01,14:23,Fixed Deposit,UPI,2573.80,Debit,26617.40,Utilities,West Bengal,767,0,NaN,0.00,Success,API,Verified,0,14

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   transaction_id         550000 non-null  object
 1   customer_id            550000 non-null  object
 2   transaction_date       550000 non-null  object
 3   transaction_time       550000 non-null  object
 4   account_type           550000 non-null  object
 5   transaction_type       550000 non-null  object
 6   transaction_amount     550000 non-null  float64
 7   transaction_direction  550000 non-null  object
 8   account_balance        550000 non-null  float64
 9   merchant_category      550000 non-null  object
 10  state                  550000 non-null  object
 11  credit_score           550000 non-null  int64
 12  has_loan               550000 non-null  int64
 13  loan_type              172866 non-null  object
 14  emi_amount             550000 non-null  float64
 15  transaction_status     550000 non-null  object
 16  channel                550000 non-null  object
 17  kyc_status             550000 non-null  object
 18  is_fraud               550000 non-null  int64
 19  transaction_hour       550000 non-null  int64
dtypes: float64(3), int64(4), object(13)
memory usage: 83.9+ MB

In [28]:
# 2. CHECK DATA
# ============================================

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())


# ============================================
# 3. MAKE A COPY FOR CLEANING
# ============================================

bank = df.copy()


# ============================================
# 4. HANDLE MISSING VALUES
# ============================================

bank["customer_id"] = bank["customer_id"].fillna("Unknown")
bank["transaction_type"] = bank["transaction_type"].fillna("Unknown")
bank["account_type"] = bank["account_type"].fillna("Unknown")
bank["merchant_category"] = bank["merchant_category"].fillna("Unknown")
bank["transaction_direction"] = bank["transaction_direction"].fillna("Unknown")

bank["transaction_amount"] = bank["transaction_amount"].fillna(0)
bank["account_balance"] = bank["account_balance"].fillna(0)


# ============================================
# 5. REMOVE DUPLICATES
# ============================================

bank.drop_duplicates(inplace=True)


# ============================================
# 6. CONVERT DATE
# ============================================

bank["transaction_date"] = pd.to_datetime(
    bank["transaction_date"],
    errors="coerce"
)


# ============================================
# 7. CLEAN COLUMN NAMES
# ============================================

bank.columns = (
    bank.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)


# ============================================
# 8. FINAL CHECK
# ============================================

print("Original rows:", len(df))
print("Cleaned rows:", len(bank))
print("Columns:", len(bank.columns))

print("\nMissing values after cleaning:")
print(bank.isnull().sum()[bank.isnull().sum() > 0])

print("\nDuplicate rows after cleaning:")
print(bank.duplicated().sum())

print("\nData types:")
print(bank.dtypes)

bank.head()

Rows: 550000
Columns: 20

Missing Values:
transaction_id                0
customer_id                   0
transaction_date              0
transaction_time              0
account_type                  0
transaction_type              0
transaction_amount            0
transaction_direction         0
account_balance               0
merchant_category             0
state                         0
credit_score                  0
has_loan                      0
loan_type                377134
emi_amount                    0
transaction_status            0
channel                       0
kyc_status                    0
is_fraud                      0
transaction_hour              0
dtype: int64

Duplicate Rows:
0
Original rows: 550000
Cleaned rows: 550000
Columns: 20

Missing values after cleaning:
loan_type    377134
dtype: int64

Duplicate rows after cleaning:
0

Data types:
transaction_id                   object
customer_id                      object
transaction_date         datetime64[ns]
transaction_time                 object
account_type                     object
transaction_type                 object
transaction_amount              float64
transaction_direction            object
account_balance                 float64
merchant_category                object
state                            object
credit_score                      int64
has_loan                          int64
loan_type                        object
emi_amount                      float64
transaction_status               object
channel                          object
kyc_status                       object
is_fraud                          int64
transaction_hour                  int64
dtype: object

,transaction_id,customer_id,transaction_date,transaction_time,account_type,transaction_type,transaction_amount,transaction_direction,account_balance,merchant_category,state,credit_score,has_loan,loan_type,emi_amount,transaction_status,channel,kyc_status,is_fraud,transaction_hour
0,TXN000000001,CUST015796,2019-01-01,15:28,Current,UPI,1820.17,Debit,609365.31,Food & Dining,Maharashtra,764,0,NaN,0.00,Success,Branch,Verified,0,15
1,TXN000000002,CUST000861,2019-01-01,03:00,Current,UPI,392.67,Credit,14451.14,Education,West Bengal,630,0,NaN,0.00,Success,Mobile_App,Verified,0,3
2,TXN000000003,CUST076821,2019-01-01,18:03,Fixed Deposit,POS,1255.97,Debit,47621.87,Utilities,Punjab,813,1,Home,1433.91,Success,Mobile_App,Verified,0,18
3,TXN000000004,CUST054887,2019-01-01,08:03,Savings,UPI,2580.68,Debit,34467.85,Travel,Karnataka,628,1,Personal,6280.35,Success,API,Verified,0,8
4,TXN000000005,CUST006266,2019-01-01,14:23,Fixed Deposit,UPI,2573.80,Debit,26617.40,Utilities,West Bengal,767,0,NaN,0.00,Success,API,Verified,0,14

In [30]:
# 9. CONNECT TO MYSQL
# ============================================

from sqlalchemy import create_engine, text

username = "root"
password = "2129"
host = "localhost"
port = 3306

In [31]:
# 10. CREATE DATABASE
# ============================================

server_engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}"
)

with server_engine.connect() as connection:
    connection.execute(
        text("CREATE DATABASE IF NOT EXISTS banking_analytics")
    )

In [32]:
# 11. CONNECT TO DATABASE
# ============================================

db_engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/banking_analytics"
)

In [33]:
# 12. LOAD DATA INTO MYSQL
# ============================================

bank.to_sql(
    "banking_transactions",
    con=db_engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)

550000

In [34]:
# 13. VERIFY MYSQL DATA
# ============================================

print(
    pd.read_sql(
        "SELECT COUNT(*) AS total_rows FROM banking_transactions",
        db_engine
    )
)

print(
    pd.read_sql(
        "SELECT * FROM banking_transactions LIMIT 5",
        db_engine
    )
)

   total_rows
0      550000
  transaction_id customer_id transaction_date transaction_time   account_type  \
0   TXN000000001  CUST015796       2019-01-01            15:28        Current
1   TXN000000002  CUST000861       2019-01-01            03:00        Current
2   TXN000000003  CUST076821       2019-01-01            18:03  Fixed Deposit
3   TXN000000004  CUST054887       2019-01-01            08:03        Savings
4   TXN000000005  CUST006266       2019-01-01            14:23  Fixed Deposit

  transaction_type  transaction_amount transaction_direction  account_balance  \
0              UPI             1820.17                 Debit        609365.31
1              UPI              392.67                Credit         14451.14
2              POS             1255.97                 Debit         47621.87
3              UPI             2580.68                 Debit         34467.85
4              UPI             2573.80                 Debit         26617.40

  merchant_category        state  credit_score  has_loan loan_type  \
0     Food & Dining  Maharashtra           764         0      None
1         Education  West Bengal           630         0      None
2         Utilities       Punjab           813         1      Home
3            Travel    Karnataka           628         1  Personal
4         Utilities  West Bengal           767         0      None

   emi_amount transaction_status     channel kyc_status  is_fraud  \
0        0.00            Success      Branch   Verified         0
1        0.00            Success  Mobile_App   Verified         0
2     1433.91            Success  Mobile_App   Verified         0
3     6280.35            Success         API   Verified         0
4        0.00            Success         API   Verified         0

   transaction_hour
0                15
1                 3
2                18
3                 8
4                14